### ISSUE TITLE
Using an apostrophe in a problem description causes it to fail to load

### ISSUE THREAD

**Issue by seieibob** [sixtycycles/airwhale#1]
If you enter something like "It's broken" into the description field of a new problem, it will silently fail to post to the server.

**Comment by sixtycycles** [comment]
i think this might have to do with `htmlspecialchars()` in the upload page.

**Comment by sixtycycles** [comment]
yeah we needed `mysqli_real_escape_string()` . im going to add this to all fields to make sure we dont break it in weird ways.

**Comment by seieibob** [comment]
I made a test marker with as many special characters as I could and it worked fine. Good job.
