### ISSUE TITLE
photos on admin page are really large. 

### ISSUE THREAD

**Issue by sixtycycles** [sixtycycles/airwhale#6]
how big should they be?

**Comment by seieibob** [comment]
Maybe put them as a thumbnail in the top-right corner of each issue? Then allow the admin to click to open the whole image in a new tab.

**Comment by seieibob** [comment]
I'll handle that one.

**Comment by sixtycycles** [comment]
awesome!

**Comment by seieibob** [comment]
Fixed by d6f1445.
